config/routes.rb
Rails.application.routes.draw do

  root 'application#welcome'
  resources :listings

  get '/login', to: 'application#login'
  post '/login', to: 'application#do_login'
  delete '/logout', to: 'application#logout'

  resources :channels do
    member do
      get 'listings/new', to: 'listings#new'
      get 'listings/show/:listing_id', to: 'listings#show'
    end
  end

end

app/models/channel.rb
class Channel < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true

  before_save :add_edit_times

  has_many :listings

  private
  def add_edit_times
    self.edit_times += 1
  end
end

app/models/listing.rb
class Listing < ActiveRecord::Base
  include HTTParty

  headers("Accept-Encoding" => "gzip", "User-Agent" => "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1700.107 Safari/537.36")
  debug_output $stdout


  belongs_to :channel
  has_many :listing_histories

  has_and_belongs_to_many :tags

  def new_history
    resp = self.class.get(url)
    history = listing_histories.build.parse(resp.body)
    history.save ? history : nil
  end
end

app/models/listing_history.rb
class ListingHistory < ActiveRecord::Base
  belongs_to :listing

  def parse(html_body)
    doc = Nokogiri::HTML(html_body)
    self.title = doc.css('#productTitle').text

    merchant_info_links = doc.css('#merchant-info a')
    self.seller_name = if merchant_info_links.size > 0
                         merchant_info_links[0].text
                       else
                         'Amazon.com'
                       end
    self.sale_rank_fragment = doc.css('#SalesRank').inner_html
    self.rating_score = doc.css('#acrPopover').attr('title').to_s.split('out of')[0].strip.to_f
    self.prod_desc = doc.css('#productDescription').inner_html
    self
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :listings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :text_cookie
  before_action :encypt_cookie
  before_action :signed_cookie
  before_action :require_login, except: [:welcome, :login, :do_login]

  def welcome
  end

  def login
  end

  def require_login
    unless login?
      flash[:danger] = "请登陆后再访问."
      cookies[:callback_url] = request.url
      logger.info("Require_login Action: #{params[:action]}")
      logger.info("Require_login Controller: #{params[:controller]}")
      redirect_to login_url
    end
  end

  def do_login
    # 做登陆操作
    sso = SsoLogin.new(params[:email], params[:password])
    if sso.verify
      cookies.signed[:username] = params[:email]
      flash[:info] = "欢迎 #{params[:email]} 回来"

      if cookies[:callback_url].nil?
        redirect_to root_url
      else
        redirect_to cookies.delete(:callback_url)
      end
    else
      flash[:danger] = "登陆失败, 因为用户名或密码错误"
      redirect_to login_url
    end
  end

  def logout
    # 做登出操作
    cookies.delete(:username)
    flash[:info] = "成功登出"
    redirect_to root_url
  end


  private
  def text_cookie
    unless cookies[:text].blank?
      cookies.delete(:text)
      logger.info("=================Delete Text Cookie===============")
    end
    nb = rand(1000)
    logger.info("Cookie Text: #{nb}")
    cookies[:text] = nb
  end

  def encypt_cookie
    unless cookies[:encrypted].blank?
      cookies.delete(:encrypted)
      logger.info("=================Delete Encrypted Cookie===============")
    end
    nb = rand(1000)
    logger.info("Cookie encrypted: #{nb}")
    cookies.encrypted[:encrypted] = nb
  end

  def signed_cookie
    unless cookies[:signed].blank?
      cookies.delete(:signed)
      logger.info("=================Delete Signed Cookie===============")
    end
    nb = rand(1000)
    logger.info("Cookie signed: #{nb}")
    cookies.signed[:signed] = nb
  end
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  def index
    @channels = Channel.all
  end

  def new
    @channel = Channel.new
  end

  def create
    @channel = Channel.new(new_channel_params)
    if @channel.save
      redirect_to @channel
    else
      render "new"
    end
  end

  def show
    @channel = Channel.find(params[:id])
  end

  def edit
    @channel = Channel.find(params[:id])
  end

  def update
    @channel = Channel.find(params[:id])
    if @channel.update(update_channel_params)
      redirect_to @channel
    else
      render "edit"
    end
  end

  def destroy
    if Channel.delete(params[:id]) <= 0
      flash[:danger] = "删除 Channel #{params[:id]} 失败"
    end
    redirect_to channels_url
  end

  private
  def new_channel_params
    params.require(:channel).permit(:name)
  end

  def update_channel_params
    params.require(:channel).permit(:name)
  end
end

app/controllers/concerns/sso_login.rb
class SsoLogin
  attr_reader :username, :password

  USER = {
      "wyatt@easya.cc" => "123456"
  }

  def initialize(username, password)
    @username = username
    @password = password
  end

  # 验证是否登陆成功?
  def verify
    user_exist? && password_correct?
  end

  private
  def user_exist?
    USER.key?(@username)
  end

  def password_correct?
    USER[@username] == @password
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params.merge(channel_id: params[:channel_id]))

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      @listing.tags.clear
      @listing.tags << Tag.find(listing_params[:tag_ids][1..-1])
      if @listing.update(listing_params.merge(channel_id: params[:channel_id]))
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_listing
    @listing = Listing.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def listing_params
    params.require(:listing).permit(:asin, :url, tag_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_tab(action)
    #controller_name == action ? 'active' : ''
    params[:controller] == action ? 'active' : ''
  end

  def login?
    !cookies[:username].nil?
  end
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/application/login.html.erb
<div class="col-md-offset-3 col-md-6">
  <% unless flash[:danger].nil? %>
    <div class="alert alert-danger" role="alert"><%= flash[:danger] %></div>
  <% end %>

  <%= form_tag(login_url, class: "form-horizontal") do %>
    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Email</label>

      <div class="col-sm-10">
        <input type="email" name="email" class="form-control" id="inputEmail3" placeholder="Email">
      </div>
    </div>
    <div class="form-group">
      <label for="inputPassword3" class="col-sm-2 control-label">Password</label>

      <div class="col-sm-10">
        <input type="password" name="password" class="form-control" id="inputPassword3" placeholder="Password">
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-default">Sign in</button>
      </div>
    </div>
  <% end %>
</div>

app/views/application/welcome.html.erb
<div class="col-md-offset-3 col-md-6 col-xs-6 font-center">
  <h2>Welcome to Etracker Demo</h2>
  <%= params %>
</div>

app/views/channels/_form.html.erb
<%= form_for(channel, html: {class: 'form-horizontal'}) do |f| %>
  <div class="form-group">
    <%= f.label :name, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: 'form-control', placeholder: 'Name' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit nil, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/channels/edit.html.erb
<% unless @channel.errors.empty? %>
  <ul class="error">
    <% @channel.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= render partial: 'form', locals: {channel: @channel} %>

<%= link_to '返回 Channel 列表', channels_url %>

app/views/channels/index.html.erb
<div class="col-xs-12 col-md-12">

  <% unless flash[:danger].blank? %>
    <div>
      <%= flash[:danger] %>
    </div>
  <% end %>

  <table class="table table-bordered table-striped">
    <tr>
      <td>#Id</td>
      <td>Name</td>
      <td>Edit Times</td>
      <td>操作</td>
    </tr>
    <%= content_tag_for(:tr, @channels) do |channel| %>
      <td><%= channel.id %></td>
      <td><%= link_to channel.name, channel_url(channel) %></td>
      <td><%= channel.edit_times %></td>
      <td>
        <%= link_to '更新', edit_channel_url(channel) %>
        <%= link_to '删除', channel_url(channel), method: :delete %>
      </td>
    <% end %>
  </table>


  <%= link_to '添加 Channel', new_channel_url %>
</div>

app/views/channels/new.html.erb
<%= render partial: 'form', locals: {channel: @channel} %>

<%= link_to '返回 Channel 列表', channels_url %>

app/views/channels/show.html.erb
I`am in channel show page and The Channel id is [<%= @channel.id %>] the name is [<%= @channel.name %>]

<br/>

<%= link_to '添加 Listing', listings_new_channel_url, class: 'btn btn-primary' %>

<br/>
<br/>
<%= link_to '返回 Channel 列表', channels_url %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EtrackerDemo</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_url %>">Etracker_Demo</a>
    </div>

    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="<%= active_tab('channels') %>">
          <a href="<%= channels_url %>">Channels 列表</a>
        </li>
        <li class="<%= active_tab('listings') %>">
          <a href="<%= listings_url %>">Listing 列表</a>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li>
          <% if login? %>
            <%= link_to '登出', logout_url, method: :delete %>
          <% else %>
            <a href="<%= login_url %>">用户登入</a>
          <% end %>
        </li>
      </ul>

    </div>
  </div>
</nav>

<% unless flash[:info].nil? %>
  <div class="alert alert-info" role="alert"><%= flash[:info] %></div>
<% end %>

<div class="container-fluid">
  <%= yield %>
</div>

</body>
</html>

app/views/listings/_form.html.erb
<%= form_for(@listing, html: {class: 'form-horizontal'}) do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
        <% @listing.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :asin, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :asin, class: 'form-control', placeholder: 'ASIN' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :url, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_area :url, class: 'form-control', placeholder: 'URL' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :tags, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.collection_select(:tag_ids, Tag.all, :id, :name, {selected: @listing.tags.ids}, {multiple: true, class: 'form-control'}) %>
    </div>
  </div>


  <%= hidden_field_tag :channel_id, params[:id] %>

  <div class="actions">
    <%= f.submit nil, class: 'btn btn-default' %>
    <%= link_to '取消', listing_url(@listing), class: 'btn btn-default' %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<div class="col-md-offset-3 col-md-6">

  <h1>Editing listing</h1>

  <%= render 'form' %>
</div>

app/views/listings/index.html.erb
<h1>Listing listings</h1>

<table class="table table-bordered">
  <thead>
  <tr>
    <td>#Id</td>
    <td>ASIN</td>
    <td>URL</td>
    <td>Channel Name</td>
    <td colspan="3">Actions</td>
  </tr>
  </thead>

  <tbody>
  <% @listings.each do |listing| %>
    <tr>
      <td><%= listing.id %></td>
      <td><%= listing.asin %></td>
      <td><%= listing.url %></td>
      <td><%= listing.channel ? listing.channel.name : '' %></td>
      <td><%= link_to 'Show', listing %></td>
      <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
      <td><%= link_to 'Destroy', listing, method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Listing', new_listing_path %>

app/views/listings/new.html.erb
<div class="col-md-offset-3 col-md-6">
  <h1>New listing</h1>

  <%= render 'form' %>

  <%= link_to 'Back', listings_path %>
</div>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

Asin: <%= @listing.asin %><br/>
URL: <%= @listing.url %><br/>

<%= link_to 'Edit', edit_listing_path(@listing) %> |
<%= link_to 'Back', listings_path %>